name: nimatf-lm
channels:
  - defaults
dependencies:
  - python==3.8.5
  - pip==20.3.3
  - pip:
    - matplotlib==3.3.3
    - jupyter==1.0.0
    - numpy==1.19.2
    - scipy==1.5.4
    - scikit-learn==0.24.0
